# Generated by Django 4.2.5 on 2023-10-02 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentData',
            fields=[
                ('URN', models.CharField(max_length=17, primary_key=True, serialize=False)),
                ('First_Name', models.CharField(max_length=45)),
                ('Middle_Name', models.CharField(max_length=45, null=True)),
                ('Last_Name', models.CharField(max_length=45)),
                ('Mother_name', models.CharField(max_length=45, null=True)),
                ('Gender', models.CharField(max_length=45)),
                ('DOB', models.DateField()),
                ('Local_Address', models.CharField(max_length=225)),
                ('Permanent_Address', models.CharField(max_length=225)),
                ('Email', models.CharField(max_length=30)),
                ('Student_Phone_No', models.IntegerField()),
                ('Emergency_Phone', models.IntegerField()),
                ('Aadhar_Card_No', models.IntegerField()),
                ('Physical_Handicap', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('Category', models.CharField(choices=[('GEN', 'GENERAL'), ('OBC', 'OBC'), ('SC', 'SC'), ('ST', 'ST'), ('EWS', 'EWS')], max_length=3)),
                ('Blood_Group', models.CharField(choices=[('O+', 'O POSITIVE'), ('O-', 'O NEGATIVE'), ('A+', 'A POSITIVE'), ('A-', 'A NEGATIVE'), ('B+', 'B POSITIVE'), ('B-', 'B NEGATIVE'), ('AB+', 'AB POSITIVE'), ('AB-', 'AB NEGATIVE'), ('BOM', 'BOMBAY')], max_length=3)),
                ('Religion', models.CharField(choices=[('HI', 'HINDU'), ('MU', 'MUSLIM'), ('CH', 'CHRISTIAN'), ('SI', 'SIKH'), ('PA', 'PARSI'), ('JE', 'JEWISH'), ('BU', 'BUDDHIST'), ('TA', 'TAOIST'), ('OT', 'OTHER')], max_length=2, null=True)),
                ('Nationality', models.CharField(max_length=45)),
                ('State_And_City', models.CharField(max_length=45)),
                ('Student_Status', models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('INACTIVE', 'INACTIVE')], max_length=8)),
                ('Academic_Year', models.IntegerField()),
                ('Program', models.CharField(max_length=45)),
                ('Course', models.CharField(max_length=45)),
                ('Semester', models.IntegerField()),
                ('Father_Occupation', models.CharField(max_length=45)),
                ('Father_Phone_No', models.IntegerField()),
                ('Father_Email_ID', models.CharField(max_length=225)),
                ('Mother_Phone_No', models.IntegerField(null=True)),
                ('Family_Income', models.IntegerField()),
                ('Education_Loan_Availed', models.CharField(choices=[('Y', 'YES'), ('N', 'NO')], max_length=1)),
                ('Photo', models.BinaryField()),
            ],
        ),
    ]
