# Generated by Django 4.2.5 on 2023-10-03 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adypu_student_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdata',
            name='Aadhar_Card_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Emergency_Phone',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Family_Income',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Father_Phone_No',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Mother_Phone_No',
            field=models.BigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Photo',
            field=models.ImageField(upload_to=''),
        ),
        migrations.AlterField(
            model_name='studentdata',
            name='Student_Phone_No',
            field=models.BigIntegerField(),
        ),
    ]
